# Generated by Django 4.2.3 on 2023-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='vehiculos/'),
            preserve_default=False,
        ),
    ]
